#!/bin/bash

# Common setup for script when copy-paste
PROJECT_NAME=stg.mdp
DIR=../${PROJECT_NAME}
BUILD_DIR=../build.${PROJECT_NAME}/

echo === ${PROJECT_NAME} RELEASE BUILD WITH UNIX MAKEFILES ===
echo === CLEANING OLD BUILD ===

[ -f ${BUILD_DIR}Makefile ] && make -C ${BUILD_DIR} --no-print-directory clean 

echo === ${PROJECT_NAME} RUNNING CMake ===

# Remove waste
[ -d ${BUILD_DIR} ] && rm -rf ${BUILD_DIR}

# Create build directory
[ ! -d ${BUILD_DIR} ] && mkdir ${BUILD_DIR}

# Do build
cd ${BUILD_DIR}
cmake   -D CMAKE_BUILD_TYPE=Debug \
        -D CMAKE_CXX_COMPILER_ARG1=-std=c++2a \
	    -D CMAKE_ECLIPSE_VERSION=4.16 \
        -G"Eclipse CDT4 - Unix Makefiles" \
        ${DIR}
cd ${DIR}

rc=$? 
if [ $rc -eq 0 ]
then
        echo === ${PROJECT_NAME} BUILD RELEASE TARGETS ===
        
        make -C ${BUILD_DIR} --no-print-directory
        rc=$?
        
        if [ $rc -eq 0 ]
        then
                echo === Build ${PROJECT_NAME} SUCCESS ===
        else
                echo === ${PROJECT_NAME} BUILD FAILS ===
                exit 1
        fi
else
        echo === ${PROJECT_NAME} CMake GENERATION FAILS ===
        exit 1
fi

exit 0
